name: run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  benchmarks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run
        run: make
